[build]
builder = "dockerfile"
dockerfilePath = "./WildRiftCounterLab.Api/Dockerfile"

[deploy]
startCommand = "dotnet WildRiftCounterLab.Api.dll" 
restartPolicyType = "always"
healthcheckPath = "/health"