<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WildRiftCounterLab.Data.Models\WildRiftCounterLab.Data.Models.csproj" />
    <ProjectReference Include="..\WildRiftCounterLab.Services.Models\WildRiftCounterLab.Services.Models.csproj" />
    <ProjectReference Include="..\WildRiftCounterLab.Common\WildRiftCounterLab.Common.csproj" />
  </ItemGroup>
</Project>
