<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mscc.GenerativeAI" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WildRiftCounterLab.Contracts\WildRiftCounterLab.Contracts.csproj" />
    <ProjectReference Include="..\WildRiftCounterLab.Services\WildRiftCounterLab.Services.csproj" />
  </ItemGroup>

</Project>
