<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WildRiftCounterLab.Services.Models\WildRiftCounterLab.Services.Models.csproj" />
    <ProjectReference Include="..\WildRiftCounterLab.Data.Models\WildRiftCounterLab.Data.Models.csproj" />
    <ProjectReference Include="..\WildRiftCounterLab.Common\WildRiftCounterLab.Common.csproj" />
    <ProjectReference Include="..\WildRiftCounterLab.Engine\WildRiftCounterLab.Engine.csproj" />
    <ProjectReference Include="..\WildRiftCounterLab.Contracts\WildRiftCounterLab.Contracts.csproj" />
  </ItemGroup>
</Project>
